# Generated by Django 3.1.13 on 2022-05-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='marketer',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
