# Generated by Django 3.1.13 on 2022-05-06 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_marketer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='marketer',
            new_name='is_marketer',
        ),
    ]
