# Generated by Django 3.1.13 on 2022-04-29 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('give_away', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='give_away')),
                ('to_keep', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='to_keep')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DaruWheelSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('refer_per', models.FloatField(blank=True, default=5, null=True)),
                ('per_to_keep', models.FloatField(blank=True, default=5, null=True)),
                ('curr_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('min_bet', models.DecimalField(blank=True, decimal_places=2, default=4, max_digits=5, null=True)),
                ('win_algo', models.IntegerField(blank=True, default=1, help_text='1=Random win_RECO,2=Using i win rate  Algo,3=Sure win_to_impress_', null=True)),
                ('trial_algo', models.IntegerField(blank=True, default=1, help_text='1=Normal win_RECO,2=Super win_to_impress,others=Use_win_algo_above', null=True)),
                ('big_win_multiplier', models.FloatField(blank=True, default=10, null=True)),
                ('virtual_acc', models.FloatField(blank=True, default=100000, null=True)),
                ('active', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'db_table': 'd_daruwheel_setup',
            },
        ),
        migrations.CreateModel(
            name='OutCome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('result', models.IntegerField(blank=True, null=True)),
                ('pointer', models.IntegerField(blank=True, null=True)),
                ('closed', models.BooleanField(blank=True, default=False, null=True)),
                ('return_per', models.FloatField(blank=True, null=True)),
                ('gain', models.DecimalField(blank=True, decimal_places=5, max_digits=100, null=True, verbose_name='gain')),
                ('active', models.BooleanField(blank=True, null=True)),
                ('win_multiplier', models.FloatField(blank=True, default=1, max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('odds', models.FloatField(blank=True, max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=50, max_digits=12, verbose_name='amount')),
                ('current_bal', models.FloatField(blank=True, default=0, max_length=10, null=True)),
                ('stake_placed', models.BooleanField(blank=True, null=True)),
                ('has_record', models.BooleanField(blank=True, null=True)),
                ('bet_on_real_account', models.BooleanField(default=False)),
                ('outcome_received', models.BooleanField(blank=True, default=False, null=True)),
                ('spinned', models.BooleanField(blank=True, default=False, null=True)),
                ('win_multiplier', models.FloatField(blank=True, default=1, max_length=10, null=True)),
                ('spinx', models.BooleanField(blank=True, default=False, null=True)),
                ('marketselection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imarketselections', to='daru_wheel.selection')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
