# Generated by Django 3.1.13 on 2022-04-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daru_wheel', '0003_daruwheelsetting_virtual_acc'),
    ]

    operations = [
        migrations.AddField(
            model_name='daruwheelsetting',
            name='active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
