# Generated by Django 3.1.13 on 2022-04-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daru_wheel', '0004_daruwheelsetting_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daruwheelsetting',
            name='active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
