# Generated by Django 3.1.13 on 2022-04-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daru_wheel', '0005_auto_20220405_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daruwheelsetting',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
