# Generated by Django 3.1.13 on 2022-04-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daru_wheel', '0006_auto_20220405_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daruwheelsetting',
            name='min_bet',
            field=models.DecimalField(blank=True, decimal_places=2, default=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='daruwheelsetting',
            name='refer_per',
            field=models.FloatField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='daruwheelsetting',
            name='virtual_acc',
            field=models.FloatField(blank=True, default=100000, null=True),
        ),
    ]
