# Generated by Django 3.1.13 on 2022-05-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daru_wheel', '0007_auto_20220416_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashstore',
            name='to_keep_marketer',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='to_keep_marketer'),
        ),
    ]
