# Generated by Django 3.1.13 on 2022-05-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daru_wheel', '0008_cashstore_to_keep_marketer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashstore',
            name='to_keep_marketer',
        ),
        migrations.AddField(
            model_name='cashstore',
            name='give_away_marketer',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='give_away_marketer'),
        ),
    ]
