# Generated by Django 3.1.13 on 2022-05-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daru_wheel', '0009_auto_20220506_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashstore',
            name='marketer_to_keep',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='marketer_to_keep'),
        ),
    ]
