# Generated by Django 3.1.13 on 2022-05-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daru_wheel', '0010_cashstore_marketer_to_keep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashstore',
            name='give_away_marketer',
        ),
        migrations.AddField(
            model_name='cashstore',
            name='marketer_give_away',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='marketer_give_away'),
        ),
    ]
