# Generated by Django 3.1.13 on 2022-04-30 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstat',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 30, 11, 31, 47, 294133), null=True),
        ),
    ]
