# Generated by Django 3.1.13 on 2022-05-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220430_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
