# Generated by Django 3.1.13 on 2022-03-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalNVP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, max_length=64)),
                ('ack', models.CharField(blank=True, max_length=32)),
                ('profilestatus', models.CharField(blank=True, max_length=32)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('profileid', models.CharField(blank=True, max_length=32)),
                ('profilereference', models.CharField(blank=True, max_length=128)),
                ('correlationid', models.CharField(blank=True, max_length=32)),
                ('token', models.CharField(blank=True, max_length=64)),
                ('payerid', models.CharField(blank=True, max_length=64)),
                ('firstname', models.CharField(blank=True, max_length=255, verbose_name='First Name')),
                ('lastname', models.CharField(blank=True, max_length=255, verbose_name='Last Name')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Street Address')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=255, verbose_name='State')),
                ('countrycode', models.CharField(blank=True, max_length=2, verbose_name='Country')),
                ('zip', models.CharField(blank=True, max_length=32, verbose_name='Postal / Zip Code')),
                ('invnum', models.CharField(blank=True, max_length=255)),
                ('custom', models.CharField(blank=True, max_length=255)),
                ('flag', models.BooleanField(blank=True, default=False)),
                ('flag_code', models.CharField(blank=True, max_length=32)),
                ('flag_info', models.TextField(blank=True)),
                ('ipaddress', models.GenericIPAddressField(blank=True, null=True)),
                ('query', models.TextField(blank=True)),
                ('response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PayPal NVP',
                'db_table': 'paypal_nvp',
            },
        ),
    ]
